version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build: 
      context: ./
      target: prod
    volumes:
    - ./:/go/src/work/
    ports:
    - 5001:5000
    - 2345:2345
    - 8080:8080
    security_opt:
    - "seccomp:unconfined"
    env_file: .env
    depends_on:
      - database
    links:
      - database
    networks:
      - default

volumes:
  data:
