version: "3"
services:
  database:
    image: postgres:13
    container_name: asciiflix_db
    restart: always
    env_file: ./config.env
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data
  video_storage:
    image: mongo
    container_name: asciiflix_videos
    restart: always
    env_file: ./config.env
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
  server:
    build:
      context: .
      args:
        - VERSION=TEST
    image: asciiflix_server
    container_name: asciiflix_server
    restart: always
    env_file: ./config.env
    depends_on:
      - database
      - video_storage
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.asciiflix_server.rule=Host(`api.asciiflix.tech`)"
      - "traefik.http.routers.asciiflix_server.entrypoints=websecure"
      - "traefik.http.routers.asciiflix_server.tls.certresolver=myhttpchallenge"
    networks:
      - backend
      - proxy

volumes:
  data:
  mongo-data:
networks:
  backend:
  proxy:
    external: true
