version: "3"
services:
  database:
    image: postgres:13
    container_name: asciiflix_db
    restart: always
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
    image: asciiflix_server
    container_name: asciiflix_server
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - database
    networks:
      - default

volumes:
  data:
