version: "3"
services:
  database:
    image: postgres:13
    container_name: asciiflix_db
    restart: always
    environment:
      - POSTGRES_DB=asciiflix_db
      - POSTGRES_USER=asciiflix
      - POSTGRES_PASSWORD=asciiflixpassword
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data
      video_storage:
        image: mongo
        restart: unless-stopped
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: fucking_change_this_to_env_file
        volumes:
          - mongo-data:/data/db
  server:
    build:
      context: .
      args:
        - VERSION=TEST
    image: asciiflix_server
    container_name: asciiflix_server
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=asciiflix_db
      - POSTGRES_USER=asciiflix
      - POSTGRES_PASSWORD=asciiflixpassword
    depends_on:
      - database
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.asciiflix_server.rule=Host(`api.asciiflix.tech`)"
      - "traefik.http.routers.asciiflix_server.entrypoints=websecure"
      - "traefik.http.routers.asciiflix_server.tls.certresolver=myhttpchallenge"
    networks:
      - backend
      - proxy

volumes:
  data:
  mongo-data:
networks:
  backend:
  proxy:
    external: true
