version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_DB=asciiflix_db
    - POSTGRES_USER=asciiflix
    - POSTGRES_PASSWORD=asciiflixpassword
    - MONGO_HOST=video_storage
    - MONGO_PORT=27017
    - MONGO_USERNAME=asciiflix
    - MONGO_PASSWORD=fucking_change_this_to_env_file
    command: /bin/zsh -c "while sleep 1000; do :; done"
  video_storage:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: asciiflix
      MONGO_INITDB_ROOT_PASSWORD: fucking_change_this_to_env_file
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=asciiflix_db
      - POSTGRES_USER=asciiflix
      - POSTGRES_PASSWORD=asciiflixpassword
      - API_PORT=8080
      - LOG_LEVEL=6
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
  mongo-data:
